name: ci

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Checkout code (full history)
      - name: Checkout
        uses: actions/checkout@v4

      # Setup golang with caching
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache-dependency-path: "**/go.sum"
          cache: true

      # Run tests
      - name: Run tests
        run: make test
