name: Go Release - Pre-Release

on:
  push:
    branches:
      - main

permissions: write-all

jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Go environment
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
          cache: true
          cache-dependency-path: "**/*.sum"

      - name: Run tests
        run: go test -cover -coverprofile=coverage.txt ./...

      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage
          path: "coverage.txt"
          if-no-files-found: error

  tinygo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
          cache-dependency-path: "**/*.sum"
          cache: true

      # Setup tinygo
      - uses: acifani/setup-tinygo@v2
        with:
          tinygo-version: "0.37.0"

      # Build fanunit firmware
      - name: Build FanUnit Firmware
        run: make build-fanunit

  # Release-please for auto-updated PRs
  release-please:
    runs-on: ubuntu-latest

    # Only create release when build and unit-tests are successful
    needs:
      - test
      - tinygo

    steps:
      - uses: googleapis/release-please-action@v3
        id: release-please
        with:
          release-type: simple # actual releasing is handled by goreleaser
          package-name: compute-blade-agent
          bump-minor-pre-major: true
